<?php
return $apartments = [
    [
        'title' => 'AirShip unico e appartato con vista mozzafiato sulle Highlands',
        'description' => 'Rifugiati sulla terrazza di questa vacanza sostenibile e ammira le scintillanti costellazioni sotto un\'accogliente coperta di tartan. AirShip 2 è un iconico chalet in alluminio isolato progettato da Roderick James con vista sul Sound of Mull dalle finestre delle dragonfly. Airship002 è comodo, eccentrico e alla moda. Non finge di essere un hotel a cinque stelle. Le recensioni raccontano la storia. Se hai prenotato le date, dai un\'occhiata al nostro nuovo annuncio The Pilot House, Drimnin, che si trova sullo stesso sito di 4 acra.',
        'price' => '195',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '50',
        'image' => 'apartments_img/apartment_1.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Igloo da neve',
        'description' => 'Igloo da neve con letti veri all\'interno. Bella atmosfera con luci a led e pareti bianche. Fuori dall\'igloo è possibile vedere l\'aurora boreale se siete fortunati. Vieni in Lapponia ed esplora la natura selvaggia. ',
        'price' => '150',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '50',
        'image' => 'apartments_img/apartment_2.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Mirror House North',
        'description' => 'Le Mirror Houses sono una coppia di case vacanza, situate nella meravigliosa cornice delle Dolomiti altoatesine, in uno splendido scenario di meli, appena fuori dalla città di Bolzano.
        Le case a specchio offrono un\'occasione unica per trascorrere una bella vacanza circondati da architettura contemporanea di altissimo livello e il paesaggio più sorprendente e la bellezza della natura ha da offrire.',
        'price' => '220',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '50',
        'image' => 'apartments_img/apartment_3.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Bumble Barn at Great Field Farm',
        'description' => 'Great Field Farm è situato in 45 ettari, tra cui giardini, paddock e il grande campo con diverse colture ogni anno.
        Bumble Barn è l\'aggiunta più recente ai nostri rifugi per vacanze eco-friendly. Costruito secondo gli standard della casa Passiv con tecnologia intelligente e un bel tetto di sedum vivente che le api amano.
        La vista dal salotto e dal patio sui campi aperti e sul cielo è mozzafiato, con la fauna selvatica tutt\' intorno.
        Veramente tranquillo e rurale, ma Canterbury, Folkestone, Hythe, tunnel della Manica a soli 10 minuti di auto.',
        'price' => '345',
        'rooms' => '3',
        'beds' => '5',
        'bathrooms' => '2',
        'square_meters' => '50',
        'image' => 'apartments_img/apartment_4.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Il Pino',
        'description' => 'Vincitore della Categoria Globale "OMG" di Airbnb
        Il Pino è la tua esperienza unica nella foresta incontaminata di Tarvisio.
        Ti permetterà di soggiornare tra le Alpi e dormire sopra le cime degli alberi, guardando le montagne illuminate dalla luce della luna.
        La baita è sviluppata su tre livelli, ognuno dei quali offre un contatto diverso con la natura.
        La struttura offre pace assoluta, non ci sono vicini e vi si accede tramite una strada sterrata privata.',
        'price' => '222',
        'rooms' => '2',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '50',
        'image' => 'apartments_img/apartment_5.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'La casetta di Aldo',
        'description' => 'Se non vi piace Cosenza è perchè non siete venuti nella casetta di Aldo!',
        'price' => '5',
        'rooms' => '6',
        'beds' => '3',
        'bathrooms' => '1',
        'square_meters' => '60',
        'image' => 'apartments_img/apartment_6.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Romantico faro di Prisnjak',
        'description' => 'Lighthouse Prisnjak è il posto unico dove trascorrere le tue vacanze. È perfettamente sistemato su una piccola isola a soli 500 metri dal mare. Questo bellissimo monumento storico è stato costruito nell\'anno 1896 ed è stato completamente ristrutturato nell\'anno 2021 per fornire sistemazioni di lusso e comfort ai suoi inquilini. Il faro è ancora in funzione. Si illumina fino al porto di Murter. Se mai sogni di svegliarti con il suono delle onde che affittano questo alloggio potrebbe realizzare i tuoi sogni.',
        'price' => '482',
        'rooms' => '3',
        'beds' => '2',
        'bathrooms' => '3',
        'square_meters' => '80',
        'image' => 'apartments_img/apartment_7.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Villa Front Lake',
        'description' => 'Villa Front Lake è una residenza di lusso senza pari sul lago di Como. Dotata di design e arredi spettacolari, viste panoramiche e splendidi giardini paesaggistici, questa storica villa con sette camere da letto offre un ambiente incomparabile di privacy e classe, rendendola forse la migliore casa vacanze per riunioni di famiglia o ospiti di matrimoni di destinazione sulle rive esclusive di Como.',
        'price' => '4816',
        'rooms' => '7',
        'beds' => '7',
        'bathrooms' => '7',
        'square_meters' => '220',
        'image' => 'apartments_img/apartment_8.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Camera matrimoniale Glicine in castello',
        'description' => 'Camera matrimoniale di lusso all\'interno dell\'appartamento del castello di Duchessa. Splendida vista sul giardino dalla camera da letto. La camera disponeva di bagno privato e aria condizionata',
        'price' => '195',
        'rooms' => '3',
        'beds' => '3',
        'bathrooms' => '1',
        'square_meters' => '60',
        'image' => 'apartments_img/apartment_9.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Villa Frascoli',
        'description' => 'Il Lago Maggiore si estende da questa imponente villa italiana, mentre le verdeggianti colline ondeggiano all\'orizzonte. Un atrio arioso, dettagliato con accenti in stile barocco, ti accoglie entrando. Gli interni sofisticati sono inondati di luce solare. Goditi un cocktail nella veranda prima di fare una piacevole passeggiata nel sontuoso giardino. Nelle vicinanze si trovano enoteche, gelaterie e caffetterie.',
        'price' => '3900',
        'rooms' => '8',
        'beds' => '11',
        'bathrooms' => '8',
        'square_meters' => '250',
        'image' => 'apartments_img/apartment_10.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Tuscany Podere nella natura con aria condizionata',
        'description' => 'Il podere si trova all\'interno di una riserva naturale. L\'abitazione si sviluppa attorno a una caratteristica corte dove si trovano la grande carraia adibita a sala da pranzo/soggiorno, tre camere matrimoniali con bagno, la lavanderia, il BBQ e il forno a legna. Al primo piano della casa si trovano la grande cucina e altre tre stanze matrimoniali sempre con servizio privato. Il grande giardino ospita una piscina a effetto lago naturale ad acqua salata con zona aeroterapia.',
        'price' => '570',
        'rooms' => '6',
        'beds' => '10',
        'bathrooms' => '7',
        'square_meters' => '140',
        'image' => 'apartments_img/apartment_11.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'KANYUMBA_REKEM',
        'description' => 'Dove passeresti il tuo prossimo inverno/estate?
        Vuoi socializzare con la natura ? in un posto bellissimo e tranquillo?
        KANYEMBA
        può offrire a te e alla tua famiglia, e il suo amico è un ottimo piano
        minimo 2 notti per poter prenotare',
        'price' => '96 ',
        'rooms' => '2',
        'beds' => '1',
        'bathrooms' => '3',
        'square_meters' => '80',
        'image' => 'apartments_img/apartment_12.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Nomadi alla fine di Chimborazo',
        'description' => 'Nomadi, l\'hotel di domani cerca di coniugare il comfort di un hotel di lusso con la cura e il rispetto per l\'ambiente utilizzando energie rinnovabili e uno speciale sistema di raccolta dei rifiuti in modo da non generare un impatto sulla terra desolata.',
        'price' => '10',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '2',
        'image' => 'apartments_img/apartment_13.web',
        'is_visible' => '1',
    ],
    [
        'title' => 'Hanok Private House',
        'description' => 'Hanok Stay Emotional Day si trova nel centro di Taejo-ro, Jeonju Hanok Village. Le attrazioni nelle vicinanze (Concubine, la Cattedrale di Jeonjeon, Gyeonggi Pre-Gyeonggi, Hyanggyo, ecc.) sono a 5 minuti di distanza.
        Si trova accanto alla strada principale, con un sacco di grucce per il cibo, ed è un soggiorno Hanok pulito e abbastanza familiare.',
        'price' => '203',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_14.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Mirror House Sud',
        'description' => 'Mirror Houses sono due casette immerse in uno stupendo scenario di meleti appena fuori a, nei meravigliosi dintorni delle Dolomiti altoatesine.
        Le Mirror Houses offrono un’occasione unica per trascorrere una stupenda vacanza circondati da architettura contemporanea dei più alti standard a stretto contatto con uno tra i più suggestivi paesaggi che la natura possa offrire.',
        'price' => '220',
        'rooms' => '2',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '110',
        'image' => 'apartments_img/apartment_15.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Marvellous lake destination eco-friendly villa',
        'description' => 'Questa lussuosa Villa eco-friendly è situata direttamente sul Lago di Como, a Brienno, con un molo privato per le barche e accesso diretto al lago con una scala in acciaio.
        La Villa è di nuova costruzione seguendo tutti i criteri di un\'ecologia di classe A+ con pannelli solari per alimentare una pompa di calore e pannelli in silicio per isolare termicamente l\'intera casa.
        Il design degli interni è bello e moderno, etichettato Lema, Cassina, B&B e Clei',
        'price' => '1280',
        'rooms' => '3',
        'beds' => '6',
        'bathrooms' => '4',
        'square_meters' => '250',
        'image' => 'apartments_img/apartment_16.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Glass House & SPA',
        'description' => 'Una casa di vetro situata su una bellissima collina nel cuore del Monferrato (patrimonio UNESCO), la Glass House offre un’incredibile vista a 360, una camera da letto ricca di comfort, un elegante soggiorno, una cucina completamente attrezzata, un bagno in marmo toscano, Sauna ed Hammam.
        È dotata di tecnologia domotica d’avanguardia, camino, TV. ecc.
        Nelle vicinanze: ottimi ristoranti, golf 36 buche, cavalli ed eccellenti cantine.
        Soggiornare nella Glass House 7* è davvero un\'esperienza unica!',
        'price' => '679',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '80',
        'image' => 'apartments_img/apartment_17.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'Trullo Luna" zona benessere e piscina',
        'description' => 'Il trullo "Luna" è situato nel cuore della Valle d’Itria, a soli 3 km dal centro di Alberobello.
        Il trullo è dotato di 1 letto matrimoniale, 1 Alcova con letto singolo, 1 bagno, zona living, cucina abitabile, sala da pranzo, TV, Wifi e AC.',
        'price' => '300',
        'rooms' => '2',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '80',
        'image' => 'apartments_img/apartment_18.webp',
        'is_visible' => '1',
    ],
    [
        'title' => 'B&B La Pusianella Suite',
        'description' => 'Il B&B La Pusianella nasce in una villa dell\'800, ristrutturata mantenendone il fascino originale. Il giardino all\'italiana si affaccia direttamente sul lago di Pusiano, uno specchio d\'acqua dall\'atmosfera rilassante. Sono disponibili 3 camere.',
        'price' => '130',
        'rooms' => '2',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '80',
        'image' => 'apartments_img/apartment_19.webp',
        'is_visible' => '1',
    ]
];
